server:
  port: ${APP_PORT:8080}
spring:
  datasource:
    url: ${UBOARD_DATABASE_URL:jdbc:postgresql://localhost:5432/uboard}
    username: ${UBOARD_DATABASE_USERNAME:postgres}
    password: ${UBOARD_DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${UBOARD_DATABASE_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${UBOARD_DATABASE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${UBOARD_DATABASE_FORMAT_SQL:false}
  application:
    name: uBoard API
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${APP_OAUTH2_JWK_ISSUER_URI:http://localhost:8181/realms/uboard}
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    vault:
      authentication: TOKEN
      token: ${UBOARD_VAULT_TOKEN}
      uri: ${UBOARD_VAULT_URI}
      config:
        lifecycle:
          enabled: true
          min-renewal: 10s
          expiry-threshold: 1m
        order: 1
  rabbitmq:
    host: ${UBOARD_RABBITMQ_HOST:localhost}
    port: ${UBOARD_RABBITMQ_PORT:5672}
    virtual-host: ${UBOARD_RABBITMQ_VIRTUAL_HOST:/}
    username: ${UBOARD_RABBITMQ_USERNAME:guest}
    password: ${UBOARD_RABBITMQ_PASSWORD:guest}

app:
  vault:
    default-path: ${UBOARD_VAULT_DEFAULT_PATH}
  configuration:
    allowed-origins: ${UBOARD_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}

uboard:
  external:
    gitlab:
      url: ${GITLAB_API_URL:https://gitlab.com}
      apiSuffix: ${GITLAB_API_SUFFIX:/api/v4}