server:
  port: ${APP_PORT:8080}
spring:
  datasource:
    url: ${UBOARD_DATABASE_URL:jdbc:postgresql://localhost:5432/uboard}
    username: ${UBOARD_DATABASE_USERNAME:postgres}
    password: ${UBOARD_DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${UBOARD_DATABASE_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${UBOARD_DATABASE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${UBOARD_DATABASE_FORMAT_SQL:false}
  application:
    name: uBoard API
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${APP_OAUTH2_JWK_ISSUER_URI:http://localhost:8181/realms/uboard}
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    vault:
      authentication: TOKEN
      token: ${UBOARD_VAULT_TOKEN}
      uri: ${UBOARD_VAULT_URI}
      config:
        lifecycle:
          enabled: true
          min-renewal: 10s
          expiry-threshold: 1m
        order: 1
  rabbitmq:
    host: ${UBOARD_RABBITMQ_HOST:localhost}
    port: ${UBOARD_RABBITMQ_PORT:5672}
    virtual-host: ${UBOARD_RABBITMQ_VIRTUAL_HOST:/}
    username: ${UBOARD_RABBITMQ_USERNAME:guest}
    password: ${UBOARD_RABBITMQ_PASSWORD:guest}
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: ${UBOARD_SCHEDULER_INITIALIZE_SCHEMA:never}
      table-prefix: qrtz_
    properties:
      org:
        quartz:
          scheduler:
            instanceId: ${UBOARD_SCHEDULER_INSTANCE_ID:AUTO}
            instanceName: ${UBOARD_SCHEDULER_INSTANCE_NAME:uboard-scheduler}
          dataSource:
            quartzDS:
              provider: hikaricp
              driver: org.postgresql.Driver
              URL: ${UBOARD_DATABASE_URL:jdbc:postgresql://localhost:5432/uboard}
              user: ${UBOARD_DATABASE_USERNAME:postgres}
              password: ${UBOARD_DATABASE_PASSWORD:root}
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: ${UBOARD_SCHEDULER_CLUSTERED:true}
            misfireThreshold: ${UBOARD_SCHEDULER_MISFIRE_THRESHOLD:60000}
            clusterCheckinInterval: ${UBOARD_SCHEDULER_CLUSTER_CHECKIN_INTERVAL:15000}
            dataSource: quartzDS
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: ${UBOARD_SCHEDULER_THREAD_COUNT:150}
logging:
  level:
    feign:
      Logger: DEBUG
    br.com.uboard: DEBUG

app:
  vault:
    default-path: ${UBOARD_VAULT_DEFAULT_PATH}
  configuration:
    allowed-origins: ${UBOARD_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}

uboard:
  external:
    gitlab:
      url: ${GITLAB_API_URL:https://gitlab.com}
      apiSuffix: ${GITLAB_API_SUFFIX:/api/v4}